application: walfasstuffs
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.+\.(gif|png|jpg|svg))$
  static_files: \1
  upload: .+\.(gif|png|jpg|svg)$
  application_readable: true

  # Serve html.
- url: /(.+\.html)$
  script: \1
  
# Serve php scripts.
- url: /(.+\.php)$
  script: \1
